{% set name = "spacy-loggers" %}
{% set modulename = "spacy_loggers" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e75d44f4cf99e6763d7132ca7c8c420e0a92790222a08bc8eb9e24ea2c13536e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
requirements:
  host:
    - python 
    - pip
  run:
    - python 
    - wasabi

test:
  imports:
    - {{ modulename }}

about:
  home: https://github.com/explosion/spacy-loggers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate loggers for spaCy pipeline training
  description: Enables alternatives to spaCy's built-in console logger
  doc_url: https://github.com/explosion/spacy-loggers
  dev_url: https://github.com/explosion/spacy-loggers

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
