{% set name = "spacy-loggers" %}
{% set modulename = "spacy_loggers" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17d0e249b2e6c6546c49fc6561a0a685f91a8edbf24a5b2b7759ead443c74654

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - python 
    - pip
  run:
    - python 
    - wasabi

test:
  imports:
    - {{ modulename }} 

about:
  home: https://github.com/explosion/spacy-loggers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate loggers for spaCy pipeline training
  description: Enables alternatives to spaCy's built-in console logger
  doc_url: https://github.com/explosion/spacy-loggers
  dev_url: https://github.com/explosion/spacy-loggers

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
